replicaCount: 2

image:
  repository: localhost:5000/mazyfood-order
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50

springBoot:
  activeProfile: postgresql

database:
  url: jdbc:postgresql://host.minikube.internal:5432/mazyfood_order
  username: mazyfood_order
  password: mazyfood_order
  driverClassName: org.postgresql.Driver

jpa:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  ddlAuto: update
  showSql: true

custom:
  persistence: postgresql
  paymentGateway: mock
